apiVersion: v1
kind: Secret
metadata:
  name: mysql-secret
  namespace: microapp

type: Opaque

stringData:
  DB_HOST: mysql-microapp.mysql.database.azure.com
  DB_NAME: microdb
  DB_USER: microappadmin
  DB_PASSWORD: YourPassword
