apiVersion: v1
kind: Secret
metadata:
  name: mysql-secret
  namespace: microapp
 
type: Opaque
 
stringData:
  DB_HOST: aksmicrosql.private.mysql.database.azure.com
  DB_NAME: microappdb
  DB_USER: microappadmin
  DB_PASSWORD: sql@12345