name: Build and Push

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - uses: azure/login@v2
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      - run: az acr login --name acrmicroapp

      - name: Build frontend
        run: |
          docker build -t acrmicroapp.azurecr.io/frontend:${{ github.sha }} ./frontend
          docker push acrmicroapp.azurecr.io/frontend:${{ github.sha }}

      - name: Build backend
        run: |
          docker build -t acrmicroapp.azurecr.io/backend:${{ github.sha }} ./backend
          docker push acrmicroapp.azurecr.io/backend:${{ github.sha }}
